### PR TITLE
Parallelised RunMCL and RunWaterfallMethod

### PR DESCRIPTION
**Pull request by sujaikumar**
1. RunMCL - run in multithreaded mode now (courtesy @esjokvist)

2. Parallelised RunWaterFallMethod (with help from @damiankao and @kashyapchhatbar for getting pathos working)
    - Needs pathos multiprocessing package - courtesy @mmckerns

            pip install git+https://github.com/uqfoundation/pathos.git@master

    - Outer loop of getting and normalising and dumping scores parallelised (idea for parallelising outer loop instead of inner loop by @DKDO
    - parallelised connect
    - parallelised writing graph (does each species separately and concatenates files at end)

Tested by comparing OrthoFinder_v0.4.0_graph.txt before and after - they were identical

### CODE REVIEW

**Comment by davidemms** [comment]
Hi
Thanks for the proposed changes for parallelising the processing of the species they look great! Did you get some measures of the performance improvements for the algorithm with the changes? 
I'd like to include the changes and will first of all look to see if I can refactor the parallelism to use the standard python multiprocessing library. One of the major selling points for OrthoFinder is that it makes it very easy for less computationally experienced users to setup and run any orthology analysis. I think this has already got a lot more people performing these kinds of analyses than were previously. For that reason I'd like to keep the number of dependencies that the user has to install to a bare minimum.
I think it should be possible to get round the problem of multiprocessing.Pool not liking instance methods by packaging up the data that the parallelised methods need instead. This should then give us the best of both worlds.
Thanks again for the changes and for your interest in the project!All the bestDavid
Date: Wed, 24 Feb 2016 07:45:24 -0800

**Comment by sujaikumar** [comment]
Hi David

I agree that using the standard python multiprocessing library would be best for the reasons you state! I didn't know how, and that's why I ended up using pathos.

Will send performance improvement numbers in a bit!

**Comment by sujaikumar** [comment]
Hi David

Here are some timings on a set of 20 proteomes (~5000-10,000 proteins each) and a subset of the first 10 proteomes, all with precomputed blasts:

File | Description | Total time
----- | ------------- | --------
| [test10_1.txt](https://github.com/davidemms/OrthoFinder/files/151279/test10_1.txt) | 10 Species original | 6m45.617s
| [test10_5.txt](https://github.com/davidemms/OrthoFinder/files/151311/test10_5.txt) | 10 Species parallelised with 5 cores | 2m28.711s
| [test10_10.txt](https://github.com/davidemms/OrthoFinder/files/151278/test10_10.txt) | 10 Species parallelised with 10 cores | 1m45.799s
| [test_20sp_new_version_1.txt](https://github.com/davidemms/OrthoFinder/files/151280/test_20sp_new_version_1.txt) | 20 Species original  | 28m7.138s
| [test_20sp_new_version_10.txt](https://github.com/davidemms/OrthoFinder/files/151345/test_20sp_new_version_10.txt) | 20 Species parallelised with 10 cores | 5m18.123s
| [test_20sp_new_version_20.txt](https://github.com/davidemms/OrthoFinder/files/151277/test_20sp_new_version_20.txt) | 20 Species parallelised with 20 cores | 4m24.289s

I was wrong when I said there was a nearly linear speedup with increased cores. The score normalising, graph connecting, graph writing are definitely running fully in parallel (all cores run at 100% when seen in top), but perhaps reading/writing .pic dumps/mcl don't speed up linearly.

Hope this helps.

Sujai

**Comment by sujaikumar** [comment]
(sorry, I closed the pull request by accident!)

**Comment by davidemms** [comment]
Hi Sujai

Thanks again to you and everyone else who did work on getting the parallelisation working! I've now incorporated this into OrthoFinder. By refactoring out some of the class structures I've also got it working using just the standard multiprocessing library and I also see the same kind of parallel speed-up you reported above. Because of the different parallelisation trade-offs for the BLAST searches and the remainder of the OrthoFinder algorithm (I think this is associated file file reading/writing) I've used separate command line arguments to control the number of threads for each of these two parts. There are also RAM considerations which benefit from this additional level of control. The new functionality is described in the README file.

All the best
David

**Pull request closed without merging**
