### PR TITLE
Added DIAMOND functionality

### PR DESCRIPTION
**Pull request by thiesgehrmann**
Hello,

I added the option to use the DIAMOND aligner instead of BLAST.
DIAMOND is many times faster than BLAST, so it speeds up the whole OrthoFinder process a lot.
DIAMOND is a drop in replacement for BLAST, so it was very easy to do.

I have not done extensive testing in terms of results of the downstream analyses, but I have run the example tests to make sure that everything works.

In this modified version, it is accessible with --diamond.
It also performs the necessary check to see if diamond is installed.

As I was using OrthoFinder as part of a pipeline, I also added the --constOut option, which reduces the working directory to Results_WorkingDirectory.
This makes retrieving output much easier in a pipeline setting.

Let me know what you think.

Cheers,
-Thies

### CODE REVIEW

**Comment by davidemms** [comment]
Hi Thies

Thanks for that, it sounds like a real improvement--the BLAST search is by far the most costly part of the OrthoFinder analysis so faster tools are a real advantage! I'll try and test it out in the next couple of weeks and push it into the master branch.

All the best
David

**Comment by mthon** [comment]
Is there a way to pull this into my local OrthoFinder repo?  I'm not too good with git/github but I'd like to try this out.

**Comment by mthon** [comment]
@thiesgehrmann I cloned your branch and ran a 4 species test set using diamond. I ran OrthoFinder like this:
./OrthoFinder/orthofinder/orthofinder.py  -f fasta --diamond

...but I got a few errors. I don't know whether it is due to diamond or not.  I'm re-running the test dataset with ncbi-blast but of course it will take some time until its done.

```
fastme -i /Users/mike/mirlo_dev/fasta/Results_Feb28/Orthologues_Feb28/WorkingDirectory/Distances/SpeciesMatrix.phy -o /Users/mike/mirlo_dev/fasta/Results_Feb28/Orthologues_Feb28/WorkingDirectory/Trees_ids/SpeciesTree_ids.txt -w O -s
2017-02-28 17:44:43 : Done 0 of 9804
2017-02-28 17:44:52 : Done 1000 of 9804
2017-02-28 17:45:02 : Done 2000 of 9804
2017-02-28 17:45:13 : Done 3000 of 9804
2017-02-28 17:45:22 : Done 4000 of 9804

 . Error: Leaf (1) '0_4951' in tree not in distance matrix.
2017-02-28 17:45:33 : Done 5000 of 9804
2017-02-28 17:45:42 : Done 6000 of 9804
2017-02-28 17:45:52 : Done 7000 of 9804
2017-02-28 17:46:02 : Done 8000 of 9804

 . Error: Leaf (2) '3_12277' in tree not in distance matrix.
2017-02-28 17:46:13 : Done 9000 of 9804

...
/Users/mike/mirlo_dev/fasta/Results_Feb28/Orthologues_Feb28/Gene_Trees/OG0009801_tree.txt
/Users/mike/mirlo_dev/fasta/Results_Feb28/Orthologues_Feb28/Gene_Trees/OG0009802_tree.txt

Best outgroup(s) for species tree
---------------------------------
Traceback (most recent call last):
  File "./OrthoFinder/orthofinder/orthofinder.py", line 1465, in <module>
    GetOrthologues(dirs, options, clustersFilename_pairs, orthogroupsResultsFilesString)
  File "./OrthoFinder/orthofinder/orthofinder.py", line 1330, in GetOrthologues
    options.constOut)
  File "/Users/mike/mirlo_dev/OrthoFinder/orthofinder/scripts/get_orthologues.py", line 762, in OrthologuesWorkflow
    roots, clusters, rootedSpeciesTreeFN, nSupport = rfd.GetRoot(spTreeFN_ids, os.path.split(db.TreeFilename_IDs(0))[0] + "/", rfd.GeneToSpecies_dash, nHighParallel, treeFmt = 1)
  File "/Users/mike/mirlo_dev/OrthoFinder/orthofinder/scripts/root_from_duplications.py", line 405, in GetRoot
    list_of_lists = pool.map(SupportedHierachies_wrapper2, [(fn, GeneToSpeciesMap, species, dict_clades, clade_names) for fn in glob.glob(treesDir + "/*")])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
```

**Comment by thiesgehrmann** [comment]
@mthon That is indeed strange. I Didn't see this error during my tests and use. How many genomes do you have?
Could you try it on an example dataset?
./orthofInder.py -f Tests/Input/ExampleDataset --diamond

**Comment by mthon** [comment]
@thiesgehrmann  I have 4 species in my data set.  The test data set ran fine.  I'm checking my input files but so far I don't  see any formatting issues. I'll continue to investigate...

**Comment by mthon** [comment]
@thiesgehrmann  @davidemms I have noticed that the Orthogroups.txt and .csv files include the protein description:
`OG0000000: gi|284811953|gb|ADB96857.1| VlhA.4.03 variable lipoprotein family pro
tein N-terminal domain protein [Mycoplasma gallisepticum str. R_low_] gi|2848119
54|gb|ADB96858.1| VlhA.4.03 variable lipoprotein family proteinC-terminal domain
 protein [Mycoplasma gallisepticum str. R_low_] gi|284811955|gb|AAP56548.2| VlhA
.4.05 variable lipoprotein family protein [Mycoplasma gallisepticum str. R_low_]
 gi|284811956|gb|ADB96859.1| VlhA.4.07.1 variable lipoprotein family protein [My
coplasma gallisepticum str. R_low_] gi|284811957|gb|ADB96860.1| VlhA.4.07.2 vari
able lipoprotein family protein N-terminal domain protein [Mycoplasma gallisepti
cum str. R_low_]`

I checked some of my previous OrthoFinder results and they only include the sequence ID (up to the first whitespace of the fasta file.  I'm on origin/master of Thies' diamond branch. This happens both with ncbi blast and with diamond blast. I tested using the test dataset theat Thies previously suggested.

**Comment by thiesgehrmann** [comment]
@mthon  I'll look into this. I also noticed this and assumed it was the standard behavior of orthofinder. I don't think I changed anything in the fasta reader, but maybe something I did had a strange interference.

**Comment by mthon** [comment]
I ran the test data set with release 1.1.4 and the output didn't have the descriptions so it must have been a change somewhere between there and the current head.

**Comment by thiesgehrmann** [comment]
@mthon I've checked and there are two places to fix this.
Either here, when reading the fasta: https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/orthofinder.py#L1298

or here, during output: https://github.com/davidemms/OrthoFinder/blob/203a861ff24b0f63aebba6c513829dff3bb3f15e/orthofinder/orthofinder.py#L99


a ".split()[0]" should do what you want.

**Comment by davidemms** [comment]
Hi 

I've been working on a mechanism to let users use whatever MSA or tree inference program they want with OrthoFinder simply by specifying in the file [config.json](https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/config.json) how the programs are called. 

The options are then added to the command line help file and you can chose which program you want to use. I thought it would be good to include diamond this way so that users can easily add other sequence search tools if they want. In fact, if you want to have your own local program settings you can put a second file in the orthofinder directory called config_user.json with the same format as the previous file. This could be useful if you wanted to have the option of calling a program with slightly different options (see diamond_more_sensitive in [config.json](https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/config.json).

I plan to revisit this next week and see if anything needs tweaking so I'd be really interested to know what you think. I'll also have a look at the other changes you implemented, I just wanted to get this part in now as I had some time to look at it and it fitted in with the other developments I'd been planing on submitting.

All the best
David

**Comment by thiesgehrmann** [comment]
Hi David,

This does seem like a much cleaner solution.
If I had done it properly, this is how I should have done it.
Because I was working time pressure, my solution was simply to hack in the diamond option. :P
A more modular approach is of course better.
I will have a look at how it works :)

Similarly, in my own working fork, I also added the option of using a different clustering algorithm, as I found that MCL was getting stuck when using several hundred species.
The algorithm is called lauvain (https://en.wikipedia.org/wiki/Louvain_Modularity).
I experimented with other community detection algorithms, but they didn't work so well.

In terms of performance, I see very good performance of (Diamond+lauvain) when compared to the original orthofinder. However, with very highly divergent genomes it becomes more difficult to separate the paralogs as well as MCL does. The clusters are still functionally consistent, though.

I have been working on evaluating the modifications I have made myself on a few datasets. If you would like to collaborate on this, I would be more than happy to. Let me know if you are interested in this.

Cheers,
-Thies

**Pull request closed without merging**
